[package]
name = "winsparkle-sys"
version = "0.1.0"
description = "Rust bindings for WinSparkle"
authors = ["hankbao84@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
