[package]
name = "sparkle-sys"
version = "0.1.0"
description = "Rust bindings for Sparkle"
authors = ["hankbao84@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = "0.2.7"
